AtividadeIntegradoraVII/Web.MVC/Controllers/LoginController.cs
namespace Web.MVC.Controllers
{
    using Infra.Contexto;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.Web.Security;
    using Dominio.Entidades;
    using Web.MVC.Models;

    public class LoginController : Controller
    {
        private readonly Contexto _contexto = new Contexto();
        // GET: Login

        [HttpGet]
        public ActionResult Index()
        {
            Session.Clear();
            return View();
        }

        public JsonResult Index(string email , string senha )
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (Membership.ValidateUser(email, senha))
                    {
                        var pessoa = _contexto.Pessoas
                            .FirstOrDefault(l => l.Email == email && l.Senha == senha);

                        var sessao = new SessionModel
                        {
                            Pessoa = pessoa,
                            IsGerente = _contexto.Gerentes.Any(l => l.PessoaId == pessoa.PessoaId)
                        };

                        Session["Sessao"] = sessao;
                        Session["Nome"] = sessao.Pessoa.Nome;
                        return Json(new
                        {
                            redirectUrl = Url.Action($"Index", $"PainelDeControle"),
                            isRedirect = true
                        });
                    }
                  
                }
                return Json(false);
            }
            catch (Exception e)
            {
                return Json(false);
                throw;
            }
          
        }
    }
}

AtividadeIntegradoraVII/Web.MVC/Controllers/UsuarioController.cs
using Dominio.Entidades;
using Infra.Contexto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.MVC.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly Contexto _contexto = new Contexto();
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public JsonResult PostCadastrar(string nome,string email,string senha,string cpf,int profissao)
        {
            try
            {
                var pessoa = new Pessoa
                {
                    Nome = nome,
                    Email = email,
                    Senha = senha,
                    Cpf = cpf
                };

                _contexto.Pessoas.Add(pessoa);
                _contexto.SaveChanges();

                switch (profissao)
                {
                    case (int) Pessoa.Profissao.Gerente:
                        var gerente = new Gerente {PessoaId = pessoa.PessoaId};
                        _contexto.Gerentes.Add(gerente);
                        break;

                    case (int) Pessoa.Profissao.Programador:
                        var programador = new Programador {PessoaId = pessoa.PessoaId};
                        _contexto.Programadores.Add(programador);
                        break;
                }
                _contexto.SaveChanges();
                LoginController login = new LoginController();
                return login.Index(pessoa.Email,pessoa.Senha);
            }
            catch (Exception er)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

AtividadeIntegradoraVII/Web.MVC/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<head>
    <meta charset="utf-8">
    <title>Login</title>
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/notify")
    @Scripts.Render("~/bundles/utils")
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.loadingoverlay/latest/loadingoverlay.min.js"></script>

</head>

<body>
    <div class="login-bg"></div>
    <div class="login-box">
        <form class="login" action="">
            <div class="logo-topo">
                <img class="img-responsive" src="~/Imagens/login-logo.png" alt="Logo">
            </div>

            <div class="form-group">
                <input type="email" required class="form-control input inLogin" id="email" placeholder="E-mail">
            </div>

            <div class="form-group">
                <input type="password" required class="form-control input inLogin" id="senha" placeholder="Senha">
            </div>

            <button type="submit" class="btn btn-send btnLogin">ENTRAR</button>
        </form>

        <div class="login-cadastrar">
            <a href="@Url.Action("Cadastrar","Usuario")" class="login-cadastrar">CADASTRAR</a>
        </div>
    </div>
</body>

<script type="text/javascript">
    $(document).ready(function () {
        $(".login").on("submit", function (event) {
            $.LoadingOverlay("show");
            login(event);
            return false;
        });
    });

    function login() {
        event.preventDefault();
        var email = $("#email").val();
        var senha = $("#senha").val();
        var url = "/Login/Index";
        $.ajax({
            type: 'POST',
            data: { 'Email': email, 'Senha': senha },
            url: url,
            dataType: 'json',
            encode: true
        }).done(function (json) {
            if (json.isRedirect) {
                window.location.href = json.redirectUrl;
            } else {
                $.LoadingOverlay("hide");
                ErroMensagem('', 'Usuário ou senha inválidos');
            }
        }).fail(function (xhr, status, error) {
            $.LoadingOverlay("hide");
            ErroMensagem('', 'Algo errado aconteceu :(');
        });
    }

</script>